### ISSUE TITLE
Upgrade without old secret key

### ISSUE THREAD

**Issue by aleclarson** [stellar/stellar-upgrade#11]
I see this tool asks for an "old secret key". But my account with STR only has a username and password, AFAIK. Would I have to contact support in that scenario?

![](https://imgur.com/JTDguSx.png)

**Comment by bartekn** [comment]
Can you send me your username to bartek at stellar?

**Comment by aleclarson** [comment]
@bartekn Sent you an email, but got no response.

**Comment by bartekn** [comment]
Haven't received it. Have you sent it to stellar.org domain?

**Comment by aleclarson** [comment]
@bartekn Ah, shit. I sent it to barktek at stellar org. 😂

**Comment by worsebit** [comment]
Hi i have the same problem @bartekn
