### ISSUE TITLE
Cannot upgrade Stellar Account -- Verification Email Not Being Sent

### ISSUE THREAD

**Issue by AumCoin** [stellar/stellar-upgrade#12]
I have attempted to upgrade multiple times.  Every time I am hit with an e-mail verification step.  No matter how many times I try, I never receive the e-mail.  Of course I have checked my Spam folder.  I don't know why Stellar is refusing to upgrade me.  My username is silverstar12980 (email silverstar1298@gmx.com).  I am reporting this as a bug because your e-mail verification system is broken.  Please fix this issue.

This is particularly upsetting because when I originally invested in the currency I was able to manage my funds online, but Stellar will no longer allow me to do so.  I feel that my currency has been stolen from me as my access to my Lumens has been removed and I am being completely denied access to my funds.

**Comment by AumCoin** [comment]
I don't know if the Stellar company is trying to insult me after stealing my money, or what is going on here.  Instead of a confirmation code I received an email entitled "Welcome to Stellar.org" containing no relevant information.  Please get in touch with me regarding this matter.  You can contact me at the e-mail on my account, as you already know.

**Comment by AumCoin** [comment]
I feel like I got screwed here and I'm not sure why, because I had this currency free and clear before, and now I do not because of your own procedures that you have introduced since.  This is my account.  I own the e-mail.  I do not know why you did not send me a confirmation code.  Please send it again.

**Comment by bartekn** [comment]
We checked the system logs. Your email server is not accepting emails from us with following error:
```
Requested action not taken: mailbox unavailable
```
The 3rd party system we used stopped delivering emails to you. Maybe it was a temporary error on your email provider side, so I removed your account from bounce list. Try again now. Will reopen if it doesn't help.

**Comment by Detergens** [comment]
@bartekn .. hello sir , i want ask about my old wallet can i ?
I have the username and password but i cant upgrade because im missing the email registred then how can i upgrade without email ? Thank you

**Comment by hoangtukai** [comment]
I did not receive my email either
My account is rivan12
and email is adriaja109@yahoo.com

**Comment by thiemthang** [comment]
hello sir.
I do not remember my password .. but I have a password reset code. Why can not I recover?
my id : thiemthang
my email : teamkhoa@gmail.com
please help me. thanks sir very muck

**Comment by bartekn** [comment]
Please use this [form](https://www.stellar.org/support-form/) to report issues with your accounts.
