### ISSUE TITLE
Cannot upgrade Stellar Account-Please contact support: hello@stellar.org

### ISSUE THREAD

**Issue by thuykenly** [stellar/stellar-upgrade#13]
Hello ! i am receiving an error message when trying to upgrade. I have emailed the department but receive no answer. A recent update was pushed through and I was able to make it one step further but then i receive the same message again. It tells me to contact hello@stellar.org

**Comment by bartekn** [comment]
Please use this form: https://www.stellar.org/support-form/

**Comment by thuykenly** [comment]
Thank you sir...

2018-01-15 22:21 GMT+07:00 Bartek Nowotarski <notifications@github.com>:
